### PR TITLE
Add initial version of 2019 report

### PR DESCRIPTION
**Pull request by brianwarner**
Initial 2019 report for review.

Signed-off-by: Brian Warner <brian@bdwarner.com>

### CODE REVIEW

**Comment by brianwarner** [comment]
Woah, massive logos.  It didn't look like that locally.  Commit coming shortly to fix it.

**Comment by caniszczyk** [comment]
good start outside the logo issue

I'd also change the title from "Annual report" to "Annual Reports"

**Comment by lucperkins** [comment]
@brianwarner These shortcodes aren't necessary, as Markdown automatically generates IDs for headers. I'd recommend removing them and using standard headers.

**Comment by brianwarner** [comment]
Cool, can do.

**Comment by caniszczyk** [comment]
can we embed the landscape image in the landscape section and link to: https://landscape.graphql.org/
https://landscape.graphql.org/images/landscape.png

**Comment by brianwarner** [comment]
@lucperkins the main reason for the shortcode was to add the top padding.  Otherwise it slips under the floating menu (at least on my local instance).  Is there a way around that?

**Comment by caniszczyk** [comment]
first bit of text is "Welcome to the [2019 GraphQL Foundation annual report]()" should be cleaned up

**Comment by lucperkins** [comment]
@brianwarner Yeah, I can fix that.

**Pull request merged**
