### PR TITLE
Add banner to news item template

### PR DESCRIPTION
**Pull request by lucperkins**
cc @acao

https://deploy-preview-30--graphql-dev.netlify.com/news/2020/04/03/web-based-graphql-ides-for-the-win-how-why-playground-graphiql-are-joining-forces/

### CODE REVIEW

**Comment by acao** [comment]
I'm not able to approve but it looks good to me!

This is coming, but we can merge your PR first when @caniszczyk has a chance to approve

https://github.com/graphql/foundation.graphql.org/pull/31

**Comment by acao** [comment]
the banner frontmatter rendering looks great to me. hopefully i can get this hugo theme working on my local, i've had success with other projects

**Comment by lucperkins** [comment]
@acao I've provided instructions in the README.

**Comment by acao** [comment]
@lucperkins indeed, tried them right away this morning, they are not working for me :/. I'll create an issue in this repo possibly, but I've already found duplicate issues with other hugo themes, spent ~3 hours working on it, has to do with the addition of `toCSS` in hugoi ~0.66 somehow. one issue suggested adding `postcss-cli`, either way I'll figure it out soon.

**Comment by lucperkins** [comment]
@acao Did you install the "extended" version of Hugo?

The site does *not* use PostCSS.

**Comment by acao** [comment]
@lucperkins that was it! oops. had grabbed the deb for hugo not hugo_extended. works a charm. thanks for all your help today!

**Comment by lucperkins** [comment]
My pleasure, @acao! Ping me if you need anything else!

**Pull request merged**
