### PR TITLE
[News] GSoD 2020 blog post

### PR DESCRIPTION
**Pull request by carolstran**
The exact same structure as Naman's blog post about GSOC - but with my story 💫 

Screen Shot 2020-09-19 at 20 23 51

Main difference between mine and Naman's is that I didn't include the GSoD logo. But I can add it if anyone feels strongly about it. Here's what it looks like:

Google Season of Docs 2020 logo

Also, I'm curious about why the massive margin between the title and post text... is it a design choice? 🤔

### CODE REVIEW

**Review by IvanGoncharov — APPROVED** [review]
@carolstran I love it!

> Also, I'm curious about why the massive margin between the title and post text... is it a design choice

Don't know 🤷‍♂️

**Comment by caniszczyk** [comment]
Awesome!

The big gap isn't a design choice, most likely a bug but my CSS skills are pretty bad :D

**Comment by carolstran** [comment]
@caniszczyk, thanks for merging! Is there anything else I need to do for this? I'd love to share it but it seems to not be on the live site 🤔

**Comment by caniszczyk** [comment]
@carolstran here you go! https://foundation.graphql.org/news/2020/09/21/google-season-of-docs-2020-participant-carolyn-stransky/

**Pull request merged**
